### ISSUE TITLE
`@warn` repetition supression is supressing other output

### ISSUE THREAD

**Issue by goretkin** [KristofferC/OhMyREPL.jl#141]
I am not sure if this is intended behavior:

```
julia> for i = 1:4; println(i, "start"); @warn(3); println(i,"end") end
1start
┌ Warning: 3
└ @ Main REPL[1]:1
1end
2start
┌ Warning: 3
└ @ Main REPL[1]:1
2end
3start
┌ Warning: 3
└ @ Main REPL[1]:1
3end
4start
┌ Warning: 3
└ @ Main REPL[1]:1
4end

julia> using OhMyREPL

julia> for i = 1:4; println(i, "start"); @warn(3); println(i,"end") end
1start
┌ Warning: 3
└ @ Main REPL[3]:1
┌ Warning: 3
└ @ Main REPL[3]:1
┌ Warning: 3
└ @ Main REPL[3]:1
┌ Warning: 3
└ @ Main REPL[3]:1
4end
```

OhMyREPL v0.4.0 on Julia 1.0.2

**Comment by KristofferC** [comment]
cc @oxinabox

**Comment by oxinabox** [comment]
So far the only way I can think of to solve this is to monkey-patch `Base.print` or `Base.write`,
in order to let the logger know that something else has been output,
and to reset the `logger.last_message_id` to say `-1` in order to disable overwritting.

**Comment by oxinabox** [comment]
Work around is to pass the `overwrite_lastlog=false`
Argument to `@warn`

See https://github.com/KristofferC/OhMyREPL.jl/blob/master/docs/src/features/logging.md

**Comment by KristofferC** [comment]
This seems kinda not so good. Could this perhaps be off by default? Interleaving logs and other output seems quite common.

**Comment by oxinabox** [comment]
To me, Interleaving logs and other output seems rare.
Because compare to `@info`, `println` is basically a low level primative.

This also  only happens if you are intervieing logs and other outputs **in a loop** (because this functionality of overwriting only occurs there.)

We could turn it off, by default. At least until we workout a better way
But it is really unfortunate for progress bar printing.


Is there a way of detecting when output is made (other than monkey patching `print`/`write` ?)
Like does the system state of the stdout device change?

**Comment by goretkin** [comment]
I could be an exaggeration, but I think the inconvenience of repeated log statements is outweighed by the possibility of hours spent on "but this code can't be executing, I put a print call here, and it's not printing", or similar. So I'm happy to see this turned off for now. Thanks!

**Comment by oxinabox** [comment]
If you are adding code for debug purposes though,
you really should be using the `@debug "" foo`, rather than `println(foo)`

And that would work fine for this.

Though I appreciate that the use of `println` debugging is pretty instinctual, 
since the new logging macros are, well, new.
