### ISSUE TITLE
CTRL-P which is history substring search in the REPL is mapped to history recall when OhMyREPL is loaded. 

### ISSUE THREAD

**Issue by ppalmes** [KristofferC/OhMyREPL.jl#169]
Is it possible to maintain the same CTRL-P which is the default behavior in Julia REPL? Also, It is quiet inconvenient to reach for arrow-keys in recalling history. Arrow keys in Macbook keyboard is difficult to reach so it will be nice if we can reassign their functionalities to the vim keybindings like CTRL-H/J/K/L.

**Comment by albheim** [comment]
Agreed, I do like the package but I have stopped using it because I like the default julia behavior. 

I looked at the code and I'm a bit curious. In julia LineEdit.jl it seems they define ctrl-p and up-arrow exactly the same, is there a reason that ctrl-p is redefined but not up-arrow? Cause up-arrow still seems to work like I would expect it in normal julia, and how I would also expect ctrl-p to work.

For now I just removed the redefinitions of ctrl-p and ctrl-n in my local ohmyrepl and it seems to work fine.
